Traceback (most recent call last):
  File "/public/home/group_zyl/.conda/envs/pt200/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/public/home/group_zyl/.conda/envs/pt200/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/public/home/group_zyl/zyl/program/Equi-MPNN/__main__.py", line 1, in <module>
    import run.train
  File "/public/home/group_zyl/zyl/program/Equi-MPNN/run/train.py", line 105, in <module>
    loss,loss_prop=loss_func(*data,weight)
  File "/public/home/group_zyl/zyl/program/Equi-MPNN/src/print_info.py", line 13, in __call__
    self.forward(iepoch,lr,loss_train,loss_val) 
  File "/public/home/group_zyl/zyl/program/Equi-MPNN/src/print_info.py", line 17, in forward
    self.ferr.write("Epoch= {:6},  lr= {:5e}  ".format(iepoch,lr))
ValueError: I/O operation on closed file.
