Traceback (most recent call last):
  File "/public/home/group_zyl/.conda/envs/pt200/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/public/home/group_zyl/.conda/envs/pt200/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/public/home/group_zyl/zyl/program/Equi-MPNN/__main__.py", line 1, in <module>
    import run.train
  File "/public/home/group_zyl/zyl/program/Equi-MPNN/run/train.py", line 97, in <module>
    if np.mod(iepoch,check_epoch)==0: scheduler(loss_val)
  File "/public/home/group_zyl/zyl/program/Equi-MPNN/src/scheduler.py", line 16, in __call__
    return self.forward(loss)
  File "/public/home/group_zyl/zyl/program/Equi-MPNN/src/scheduler.py", line 19, in forward
    if loss>10.0*self.best_loss or loss.isnan():
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
